version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    labels:
      - dependencies
    groups:
      npm-development-dependencies:
        dependency-type: development
        patterns:
          - "*"

  # Dependabot supports Docker image tags in Kubernetes manifests.
  - package-ecosystem: docker
    directories:
      - /examples/hello-app/base
      - /examples/podinfo
      - /examples/redis
      - /examples/cronjob
      - /examples/blue-green
      - /examples/web-server
      - /examples/multi-tier
      - /examples/rolling-update
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    labels:
      - dependencies
    groups:
      container-images:
        patterns:
          - "*"
