apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tutorial-examples
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - name: configmap
            path: examples/configmap
          - name: web-server
            path: examples/web-server
          - name: podinfo
            path: examples/podinfo
          - name: cronjob
            path: examples/cronjob
  template:
    metadata:
      name: "example-{{.name}}"
      labels:
        app.kubernetes.io/part-of: argocd-local-tutorial
        tutorial.argocd.io/difficulty: simple
        tutorial.argocd.io/example: "{{.name}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: local-tutorial
      source:
        repoURL: https://github.com/marcincuber/argocd.git
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "tutorial-{{.name}}"
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            app.kubernetes.io/managed-by: argocd
            tutorial.argocd.io/difficulty: simple
            tutorial.argocd.io/example: "{{.name}}"
        automated:
          enabled: true
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 5
