apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: web-content
    literals:
      - index.html=<h1>Simple web server</h1><p>Deployed by Argo CD.</p>
