apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/part-of: argocd-local-tutorial
spec:
  selector:
    app.kubernetes.io/name: web-server
  ports:
    - name: http
      port: 80
      targetPort: http
