apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rolling-update
  labels:
    app.kubernetes.io/name: rolling-update
    app.kubernetes.io/part-of: argocd-local-tutorial
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rolling-update
