apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - prune-demo.yaml
  - service.yaml

configMapGenerator:
  - name: hello-content
    files:
      - index.html=content/index.html

labels:
  - pairs:
      app.kubernetes.io/name: hello-minikube
      app.kubernetes.io/part-of: argocd-local-tutorial
    includeSelectors: true
    includeTemplates: true
