apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: hello-minikube
    count: 3

labels:
  - pairs:
      tutorial.argocd.io/environment: staging
    includeSelectors: false
    includeTemplates: true
